### ISSUE TITLE
Support startRow 0 for limit

### ISSUE THREAD

**Issue by AdeelK93** [arontsang/ag-grid-duckdb-datasource#2]
Hey @arontsang, this is a really neat library!
I found a bug [here](https://github.com/arontsang/ag-grid-duckdb-datasource/blob/main/src/query/index.ts#L91) - since 0 is falsey, no limit is being applied. The correct if statement should be `request.startRow !== undefined && request.endRow !== undefined`

**Comment by arontsang** [comment]
Damnit JavaScript

**Comment by arontsang** [comment]
@AdeelK93 Can you check if this fixes the bug.

Editing on mobile.
